app/models.py
from app import db, login_manager
from datetime import datetime
from flask_bcrypt import generate_password_hash, check_password_hash
from flask_login import UserMixin

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), unique=True, nullable=False)
    birth_date = db.Column(db.Date())
    password = db.Column(db.String(128), nullable=False)

    def set_password(self, password):
        self.password = generate_password_hash(password).decode('utf-8')

    def check_password(self, password):
        return check_password_hash(self.password, password)


@login_manager.user_loader
def user_loader(user_id):
    return User.query.get(int(user_id))

# class Post(db.Model):
#     id = db.Column(db.Integer, primary_key=True)
#     title = db.Column(db.String(64), nullable=False)
#     content = db.Column(db.Text, nullable=False)
#     time_stamp = db.Column(db.DateTime(), default=datetime.utcnow)
#     user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from config import Config


app = Flask(__name__)
app.config.from_object(Config)
db = SQLAlchemy(app)
migrate = Migrate(app, db)
login_manager = LoginManager(app)
login_manager.login_view = 'auth.login'

from app import models

from app.auth import bp as auth_bp
app.register_blueprint(auth_bp, url_prefix='/auth')

from app.main import bp as main_bp
app.register_blueprint(main_bp, url_prefix='/')

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import views

app/main/views.py
from flask import render_template, flash, redirect, url_for

from app.main import bp

@bp.route('/')
@bp.route('index')
def index():
    return render_template('main/index.html')

app/templates/layout.html
<!doctype html>
<html>

   <head>

      <title>{% block title %} {% endblock %}MAC Forum</title>
      <link rel="stylesheet" type="text/css" href="/static/css/main.css" />

   </head>
   <body>
     <div id='header'>

       <div class='container'>

         <div class='float-left'>
           <a href="#"><img src="/static/images/logo.png"></a>
         </div>

         <div class='float-right'>
             <ul>
                 <li> <a href="{{ url_for('main.index') }}" >Home</a> </li>
                 {% if current_user.is_anonymous %}
                     <li> <a href="{{ url_for('auth.login') }}"> Login</a></li>
                     <li> <a href="{{ url_for('auth.register') }}"> Register</a></li>

                 {% else %}
                     <li> <a href="{{ url_for('auth.logout') }}"> Logout</a></li>
                 {% endif %}
             </ul>
         </div>

       </div>

     </div>

      <div id='main'>
        <div class='container'>
            {% block main_title %} {% endblock %}

            {% with messages = get_flashed_messages() %}
                {% for message in messages %}
                    <p id="flash">{{ message }}</p>
                {% endfor %}
            {% endwith %}

            {% block main %} {% endblock %}
        </div>
      </div>

      <div id='footer'>
        <div class="container">
          <p style="float:left"> Made with love </p>
          <p style="float:right"> <i>by lololol</i> </p>
        </div>
      </div>


   </body>
</html>

app/templates/main/index.html
{% extends "layout.html" %}

{% block main_title %}<h1>Main Page</h1>{% endblock %}

{% block main %}

{% endblock %}